<x-guest-layout>

    @push('css')
        @vite(['resources/css/3.css'])
    @endpush

    @push('scripts')
        <script src="{{ asset('static/runtime.7c6b2c574cb255b04c4f.js') }}"></script>
        <script src="{{ asset('static/vendor.148b142df29c0644a491.js') }}"></script>
        <script src="{{ asset('static/3.d15a3fea6c61801c0cfa.js') }}"></script>
        <script src="{{ asset('static/legacy-components.1cbfaef53573c17aab6b.js') }}"></script>
    @endpush

    <div class="Pane Pane--underSiteNav Pane--repeat hide" data-url="https://bnetcmsus-a.akamaihd.net/cms/template_resource/uj/UJX9EMWHIBFE1466177294042.jpg" media-medium="hide" queryselectoralways="0 31" media-original="Pane Pane--underSiteNav Pane--repeat">
        <div class="Pane-bg" style="background-color:#041828;background-image:url(&quot;https://bnetcmsus-a.akamaihd.net/cms/template_resource/uj/UJX9EMWHIBFE1466177294042.jpg&quot;);"><div class="Pane-overlay"></div></div><div class="Pane-content"><div class="space-medium"></div><div class="space-small"></div><div class="contain-small"><div class="contain-masthead"><div class="space-small"></div><div class="font-bliz-light-small-gray">Все в порядке.</div><div class="space-small"></div><div class="font-semp-large-white">500: сбой на сервере</div></div><div class="space-small"></div><div class="space-small"></div><div class="Divider Divider--lightBrown Divider--thin"></div><div class="space-small"></div><div class="color-monochrome-white">Сервер, похоже, перегружен. Пустяки, дело житейское! Пока можно вот куда заглянуть.</div><div class="space-small"></div><div class="Divider Divider--lightBrown Divider--thin"></div><div class="space-small"></div><div class="List List--left List--separator List--separatorBrownMedium gutter-small gutter-vertical"><div class="List-item gutter-small"><a class="Link Link--text" href="/ru-ru/">Главная</a></div><div class="List-item gutter-small"><a class="Link Link--external Link--text" href="https://battle.net/account/">Учетная запись</a></div><div class="List-item gutter-small"><a class="Link Link--external Link--text" href="https://shop.battle.net/family/world-of-warcraft">Магазин</a></div><div class="List-item gutter-small"><a class="Link Link--external Link--text" href="https://battle.net/support/">Поддержка</a></div></div></div><div class="contain-small"><div class="space-small"></div><div class="gutter-small"><div class="Art" queryselectoralways="4"><div class="Art-size" style="padding-top:56.1877667140825%"></div><div class="Art-image" style="background-image:url(https://bnetcmsus-a.akamaihd.net/cms/template_resource/OVJTYDLXLXGD1462320129700.jpg);"></div><div class="Art-overlay"></div></div></div><div class="space-large"></div></div></div></div>
    <div class="Pane Pane--underSiteNav" data-url="https://bnetcmsus-a.akamaihd.net/cms/template_resource/RHMX56JT07891461948685993.jpg" media-medium="!hide" queryselectoralways="0 31" media-original="Pane Pane--underSiteNav hide"><div class="Pane-bg" style="background-color:#041828;background-image:url(&quot;https://bnetcmsus-a.akamaihd.net/cms/template_resource/RHMX56JT07891461948685993.jpg&quot;);"><div class="Pane-overlay"></div></div><div class="Pane-content"><div class="space-large"></div><div class="Box Box--overlayDark align-left contain-small contain-right contain-medium" media-wide="contain-medium" queryselectoralways="0" media-original="Box Box--overlayDark align-left contain-small contain-right"><div class="contain-masthead"><div class="space-small"></div><div class="font-bliz-light-small-gray">Все в порядке.</div><div class="space-small"></div><div class="font-semp-large-white">500: сбой на сервере</div></div><div class="space-small"></div><div class="space-small"></div><div class="Divider Divider--lightBrown Divider--thin"></div><div class="space-small"></div><div class="color-monochrome-white">Сервер, похоже, перегружен. Пустяки, дело житейское! Пока можно вот куда заглянуть.</div><div class="space-small"></div><div class="Divider Divider--lightBrown Divider--thin"></div><div class="space-small"></div><div class="List List--left List--separator List--separatorBrownMedium gutter-small gutter-vertical"><div class="List-item gutter-small"><a class="Link Link--text" href="/ru-ru/">Главная</a></div><div class="List-item gutter-small"><a class="Link Link--external Link--text" href="https://battle.net/account/">Учетная запись</a></div><div class="List-item gutter-small"><a class="Link Link--external Link--text" href="https://shop.battle.net/family/world-of-warcraft">Магазин</a></div><div class="List-item gutter-small"><a class="Link Link--external Link--text" href="https://battle.net/support/">Поддержка</a></div></div></div><div class="space-huge"></div><div class="space-huge"></div><div class="space-huge"></div><div class="space-huge"></div><div class="space-huge"></div><div class="space-large"></div></div></div>
</x-guest-layout>
