<div class="Divider"></div>
<div class="Pane Pane--bgBottom bordered" data-lazyload-modifier="Pane--dirtLight">
    <div class="Pane-bg">
        <div class="Pane-overlay"></div>
    </div>
    <div class="Pane-content">
        <div class="gutter-normal gutter-vertical">
            <div class="SocialLinks SocialLinks--wow">
                <div class="SocialLinks-title">Warcraft в соцсетях</div>
                <div class="SocialLinks-links">
                    <a class="Link SocialLinks-link" href="https://www.facebook.com/WorldofWarcraft.ru" data-analytics="sns-refer" data-analytics-placement="Footer - facebook"><span class="Icon Icon--social-facebook Icon--medium SocialLinks-icon"><svg class="Icon-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 64" focusable="false"><use xlink:href="/static/components/Icon/svg/social-facebook.20d2ed4f5a690fe838af4c2beb4ba8be.svg#social-facebook"></use></svg></span></a><a class="Link SocialLinks-link" href="http://twitter.com/warcraft_RU" data-analytics="sns-refer" data-analytics-placement="Footer - twitter"><span class="Icon Icon--social-twitter Icon--medium SocialLinks-icon"><svg class="Icon-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 64" focusable="false"><use xlink:href="/static/components/Icon/svg/social-twitter.fe8ef9d809c5b5099e326f60b39ff940.svg#social-twitter"></use></svg></span></a><a class="Link SocialLinks-link" href="https://www.youtube.com/user/WorldofWarcraftRU" data-analytics="sns-refer" data-analytics-placement="Footer - youtube"><span class="Icon Icon--social-youtube Icon--medium SocialLinks-icon"><svg class="Icon-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 64" focusable="false"><use xlink:href="/static/components/Icon/svg/social-youtube.f56a46d1a6cc2ffd841bc4a8d1de3d3d.svg#social-youtube"></use></svg></span></a><a class="Link SocialLinks-link" href="https://www.reddit.com/r/wow" data-analytics="sns-refer" data-analytics-placement="Footer - reddit"><span class="Icon Icon--social-reddit Icon--medium SocialLinks-icon"><svg class="Icon-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 64" focusable="false"><use xlink:href="/static/components/Icon/svg/social-reddit.c70b106f4cf581aae6b314f337d07921.svg#social-reddit"></use></svg></span></a><a class="Link SocialLinks-link" href="http://vk.com/worldofwarcraft" data-analytics="sns-refer" data-analytics-placement="Footer - vkontakte"><span class="Icon Icon--social-vkontakte Icon--medium SocialLinks-icon"><svg class="Icon-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 64" focusable="false"><use xlink:href="/static/components/Icon/svg/social-vkontakte.57ff1545fb0a71780640cc4f07ad2be3.svg#social-vkontakte"></use></svg></span></a><a class="Link SocialLinks-link" href="https://www.instagram.com/warcraft" data-analytics="sns-refer" data-analytics-placement="Footer - instagram"><span class="Icon Icon--social-instagram Icon--medium SocialLinks-icon"><svg class="Icon-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 64" focusable="false"><use xlink:href="/static/components/Icon/svg/social-instagram.d8f4f26719bf05eaaa420654df619d00.svg#social-instagram"></use></svg></span></a></div>
            </div>
        </div>
    </div>
</div>
